### ISSUE TITLE
Nibe FLM, missing register "47260"

### ISSUE THREAD

**Issue by supergregg** [anerdins/nibepi#13]
I have a Nibe 1255 with an FLM but the config for the 1255 is missing register "47260". It has 47261,47262,47263,47264 to R/W the Fan speed settings but missing the "selector" register. It was easy enough to manually just copy this line from the F370 and put it in the file but I think it should be there for every heatpump that is compatible with the FLM.
According to the datasheed of the FLM, compatible heatpumups are:

F1145, F1155, F1245, F1255, F1345, F1355

**Comment by anerdins** [comment]
Thanks, this will be resolved in an updated image soon.
