### ISSUE TITLE
SSH into the Pi

### ISSUE THREAD

**Issue by krambriw** [anerdins/nibepi#17]
Hi, impressive project!!

How do I ssh into the os so I can start raspi-config, expand the sd-card, set fixed ip, enable vnc

Best regards, Walter

**Comment by anerdins** [comment]
You can access the ssh interface with pi / nibe

 

Från: Walter Krämbring ***@***.***> 
Skickat: den 20 september 2022 19:29
Till: anerdins/nibepi ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: [anerdins/nibepi] SSH into the Pi (Issue #17)

 

Hi, impressive project!!

How do I ssh into the os so I can start raspi-config, expand the sd-card, set fixed ip, enable vnc

Best regards, Walter
