### ISSUE TITLE
Issue with Novelan (same HW as Nibe) heatpump

### ISSUE THREAD

**Issue by martinarva** [anerdins/nibepi#22]
Nibe

Hi! First of all, thank you for the work you have done.

I have Novelan L12 Split air-water heatpump (https://www.novelan.at/start/produkte/luftwasser-waermepumpen-aussenaufstellung/detailseite/l12-split-hv-12.html)

This has the same hardware as Nibe BA-SVM 10-200  (https://volundvt.dk/produkter/luft-til-vand-varmepumpe/sortimentsoversigt/produkt/nibe-split-med-ba-svm-10-200)

Even the modbus accessory is the same as NIbes Modbus 40 and the pinouts are the same as in NibePi installation manual. Here is the link for Novelan modbus manual - https://kesko-onninen-pim-resources-production.s3-eu-west-1.amazonaws.com/pimdocuments/16429139.pdf)  So to my understanding NibePi should work with my Novelan unit.  I installed NibePI to Rasperry Pi4 and using USB RS485 dongle to connect to heatpump. Only thing i had to to is change ttyAMA0 to /dev/ttyUSB0 in the configuration. Activated modbus from the  heatpump service menu. At first heatpumo gave me error that modbus is not connected. Then i swapped A and B pins and error went away

I activated logging and got some raw data from the heatpump and some of it had even ok and sent status. Here is a log after last restart: https://pastebin.com/9cZktGjj

As you can see from the log file, NibePi restarts a t some frequency when “file truncated” pops up.

So what I have achieved: 
1. NibePI installed 2. USB RS485 works
3. Connection to my heatpump works eg. I dont get the modbus error from the pump side
4. I get raw data from heatpump 

Problems
1. no data in NibePi
2. NibePi crashes and restart

My questions
1. Are there any hints in the logging? Should I log more?
2. Am I doing something else wrong?

**Comment by anerdins** [comment]
Fixed in 1.2.1 branch with the help of the information. Heatpump is now supported.
